// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/belalmoh/commercia/src/internal/application/services"
	"github.com/belalmoh/commercia/src/internal/infrastructure/database"
	"github.com/belalmoh/commercia/src/internal/infrastructure/database/repositories"
	"github.com/belalmoh/commercia/src/internal/infrastructure/server"
	"github.com/belalmoh/commercia/src/internal/presentation"
	"github.com/belalmoh/commercia/src/internal/presentation/controllers"
)

// Injectors from wire.go:

func InitServer() *server.Server {
	engine := server.NewGinEngine()
	connection := database.NewConnection()
	db := connection.GetDB()
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(userRepository)
	userController := controllers.NewUserController(userService)
	router := presentation.NewRouter(userController)
	serverServer := server.NewServer(engine, router)
	return serverServer
}
