services:
  commercia-db:
    image: postgres:16-alpine
    container_name: commercia-db
    environment:
      POSTGRES_DB: commercia
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - commercia-network

volumes:
  postgres_data:

networks:
  commercia-network:
    driver: bridge
